DROP DATABASE IF EXISTS EmpresaG6;
CREATE DATABASE EmpresaG6;
USE EmpresaG6;

CREATE TABLE Vehiculos(
Matricula VARCHAR(10) NOT NULL PRIMARY KEY,
num_Bastidor VARCHAR(20) NOT NULL,
color VARCHAR(10) NOT NULL,
num_Asientos INTEGER(2) NOT NULL,
precio DOUBLE NOT NULL,
serie VARCHAR(10) NOT NULL,
Tipo_Vehiculo VARCHAR(6) NOT NULL
);

CREATE TABLE Coches(
Matricula VARCHAR(10) NOT NULL PRIMARY KEY,
num_Puertas INTEGER(1) NOT NULL,
capacidad_Maletero_dm3 DOUBLE NOT NULL,
FOREIGN KEY (Matricula) REFERENCES Vehiculos(Matricula)
ON DELETE CASCADE
);

CREATE TABLE Camiones(
Matricula VARCHAR(10) NOT NULL PRIMARY KEY,
carga_kg DOUBLE NOT NULL,
tipo_Mercancia VARCHAR(1) NOT NULL,
FOREIGN KEY (Matricula) REFERENCES Vehiculos(Matricula)
ON DELETE CASCADE
);

CREATE TABLE Series(
Nombre_Serie VARCHAR(15) PRIMARY KEY NOT NULL,
Marca VARCHAR(15) NOT NULL,
Modelo VARCHAR(15) NOT NULL,
Anio_Fabricacion INTEGER(4) NOT NULL
);

CREATE TABLE Historial(
Fecha DATETIME NOT NULL PRIMARY KEY,
Matricula VARCHAR(10) NOT NULL,
num_Bastidor VARCHAR(20) NOT NULL,
color VARCHAR(10) NOT NULL,
num_Asientos INTEGER(2) NOT NULL,
precio DOUBLE NOT NULL,
serie VARCHAR(10) NOT NULL,
Tipo_Vehiculo VARCHAR(6) NOT NULL,
Descripcion VARCHAR(25) NOT NULL
);
